defmodule MySportsFeeds.Entities.Stats.Batting do
  @derive [Poison.Encoder]
  defstruct [
      atBats: nil, #0,
      runs: nil, #0,
      hits: nil, #0,
      secondBaseHits: nil, #0,
      thirdBaseHits: nil, #0,
      homeruns: nil, #0,
      earnedRuns: nil, #0,
      unearnedRuns: nil, #0,
      runsBattedIn: nil, #0,
      batterWalks: nil, #0,
      batterSwings: nil, #0,
      batterStrikes: nil, #0,
      batterStrikesFoul: nil, #0,
      batterStrikesMiss: nil, #0,
      batterStrikesLooking: nil, #0,
      batterTagOuts: nil, #0,
      batterForceOuts: nil, #0,
      batterPutOuts: nil, #0,
      batterGroundBalls: nil, #0,
      batterFlyBalls: nil, #0,
      batterLineDrives: nil, #0,
      batter2SeamFastballs: nil, #0,
      batter4SeamFastballs: nil, #0,
      batterCurveballs: nil, #0,
      batterChangeups: nil, #0,
      batterCutters: nil, #0,
      batterSliders: nil, #0,
      batterSinkers: nil, #0,
      batterSplitters: nil, #0,
      batterStrikeouts: nil, #0,
      stolenBases: nil, #0,
      caughtBaseSteals: nil, #0,
      batterStolenBasePct: nil, #0,
      battingAvg: nil, #0,
      batterOnBasePct: nil, #0,
      batterSluggingPct: nil, #0,
      batterOnBasePlusSluggingPct: nil, #0,
      batterIntentionalWalks: nil, #0,
      hitByPitch: nil, #0,
      batterSacrificeBunts: nil, #0,
      batterSacrificeFlies: nil, #0,
      totalBases: nil, #0,
      extraBaseHits: nil, #0,
      batterDoublePlays: nil, #0,
      batterTriplePlays: nil, #0,
      batterGroundOuts: nil, #0,
      batterFlyOuts: nil, #0,
      batterGroundOutToFlyOutRatio: nil, #0,
      pitchesFaced: nil, #0,
      plateAppearances: nil, #0,
      leftOnBase: nil, #0
  ]

end